"""Serialization helpers and classification model comparison."""

import pickle
from pathlib import Path

import numpy as np
import yaml
from sklearn.model_selection import GridSearchCV, StratifiedKFold


def read_yaml_file(file_path):
    """Read a YAML configuration using the safe loader."""
    return yaml.safe_load(Path(file_path).read_text(encoding="utf-8"))


def write_yaml_file(file_path, content, replace=False):
    """Write a report, creating its parent directory as needed."""
    path = Path(file_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(content, sort_keys=False), encoding="utf-8")


def save_numpy_array_data(file_path, array):
    """Persist a numeric array without pickle metadata."""
    Path(file_path).parent.mkdir(parents=True, exist_ok=True)
    with open(file_path, "wb") as stream:
        np.save(stream, array, allow_pickle=False)


def load_numpy_array_data(file_path):
    """Read an array generated by the training pipeline."""
    return np.load(file_path, allow_pickle=False)


def save_object(file_path, obj):
    """Serialize an internal artifact; never accept pickle uploads from users."""
    Path(file_path).parent.mkdir(parents=True, exist_ok=True)
    with open(file_path, "wb") as stream:
        pickle.dump(obj, stream)


def load_object(file_path):
    """Load only trusted local artifacts produced with matching dependency versions."""
    with open(file_path, "rb") as stream:
        return pickle.load(stream)


def evaluate_models(X_train, y_train, models, param):
    """Rank pipelines by training-only cross-validation F1; never inspect the holdout."""
    report = {}
    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    for name, model in models.items():
        search = GridSearchCV(model, param[name], scoring="f1", cv=cv, n_jobs=1)
        search.fit(X_train, y_train)
        models[name] = search.best_estimator_
        report[name] = float(search.best_score_)
    return report
